### ISSUE TITLE
Использовать DataSource из сервера приложений

### ISSUE THREAD

**Issue by AlphaBeth** [cuteWarmFrog/web3#11]
1. Настроить datasource в сервере приложений, который работает с нужной базой данных (возможно, вот это вот https://www.stenusys.com/how_to_setup_postgresql_datasource_with_wildfly/)
2. Получить DataSource в бине, работающим с БД (например, сделать ApplicationScoped/NoneScoped бин, внутри которого будет поле с аннотацией `@Resource`, в которой вы укажете jndi для созданного datasource
3. Использовать это поле в бине

**Comment by cuteWarmFrog** [comment]
@AlphaBeth Я короче уже не верил в то, что я это сделаю, но боги были милостливы ко мне. В целом, из-за невнимательности я потерял около месяца -______-
